### PR TITLE
fix: middleware returns 404 with `new NextResponse` on invalid route

### LINKED ISSUE #341: [🐛 Bug]: new NextResponse() ignoring 2xx status codes, always returning 404
### next-on-pages environment related information

`"@cloudflare/next-on-pages": "0.0.0-f879ffd"`

### Description

Returning a new Response with a status code of 200 will always return status code 404.

E.g:

```
return new NextResponse(
      `Hello, world`,
      {
        status: 200,
        headers: {
          'content-type': 'text/html',
        },
      },
    )
```

If you return a status code of 400 it will work, but a 200 status code does not and will always result in 404.

The bug seems to be caused by this line:
https://github.com/cloudflare/next-on-pages/blob/f879ffd7f6031bdff6420ad53047aa31c3c39f97/packages/next-on-pages/templates/_worker.js/routes-matcher.ts#L564

Removing the `this.status < 400` check fixes the issue, but I assume this is here for other reasons.

### Reproduction

_No response_

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

_No response_

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by james-elicx**
This PR does the following:
- Ensures we bail out of routing when a middleware response is present

Previously, we added a fix to bail out of routing when running a middleware returned a response. However, this change didn't account for when the request was to a route that doesn't exist in the build output. This fix ensures that it always bails out when a user returns `new NextResponse`, regardless of if the target route is in the build output. This is the correct behaviour that should have happened before 🙈

fixes #341

### CODE REVIEW

File: packages/next-on-pages/templates/_worker.js/routes-matcher.ts [hunk 1]
```diff
@@ -537,11 +537,12 @@ export class RoutesMatcher {
...
 		}
 
-		// In the `hit` phase or for external urls/redirects, return the match.
+		// In the `hit` phase or for external urls/redirects/middleware responses, return the match.
 		if (
 			phase === 'hit' ||
 			isUrl(this.path) ||
-			this.headers.normal.has('location')
+			this.headers.normal.has('location') ||
+			!!this.body
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/routes-matcher.ts:545]: so if `this.body` if defined here we always want to bail out, is that correct?

do you think that this can have unintended consequences? (i.e. can we get a truthy `this.body` and not want to bail out?)

Comment (james-elicx) [reply packages/next-on-pages/templates/_worker.js/routes-matcher.ts:545]: That is correct. There should be no unintended consequences. The value for `this.body` is only ever set when a middleware returns a response that is supposed to be returned to the client.

Comment (dario-piotrowicz) [reply packages/next-on-pages/templates/_worker.js/routes-matcher.ts:545]: awesome thanks 🙂

**Review by dario-piotrowicz — APPROVED** [review]
Thanks @james-elicx 😄
