### PR TITLE
Use pmm again

### LINKED ISSUE #467: [🐛 Bug]: Command does not work with monorepos x yarn berry
### next-on-pages environment related information
Using version `@cloudflare/next-on-pages@1.6.1`
```
~/sites/edge-compute-poc$ yarn web next-on-pages --info
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '.yarnrc.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.yarnrc.yml'
}
```

### Description

Currently `next-on-pages` assumes the `.yarnrc.yml` is always present in directory from where the script is ran. [See here](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/src/buildApplication/packageManagerUtils.ts#L43)

When having a monorepo (for example with Turborepo) we have the following structure:
```
- apps
 - web
  - {nextjs project}
- .yarnrc.yml
```

This will not work since the script is executed in `apps/web` and currently the file is 2 directories higher.
As a dirty hack, changing the patch to `../../.yarnrc.yml` makes the script run successfully.

### Reproduction

1. Create a monorepo using `npx create-turbo@latest`
2. Select `yarn` as package manager
3. Go into the created project folder
4. Run `yarn set version 3.3.1`
5. Run `yarn workspace web dlx @cloudflare/next-on-pages@1` to run the cloudflare pages build script
6. Be greeted with the following error ```⚡️ Watch mode unexpected error: Error: ENOENT: no such file or directory, open '.yarnrc.yml'```

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

I used `yarn patch @cloudflare/next-on-pages`, then follow the instructions in the terminal. The file you need to look for is the `dist/index.js` and then search for `".yarnrc.yml"` and change it to `"../../.yarnrc.yml"`.

After changing, "commit" the yarn patch as the terminal describes it and run `yarn install` again. You will now see the commands correctly work.

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
fixes #467

### CODE REVIEW

File: packages/next-on-pages/src/buildApplication/buildVercelOutput.ts [hunk 1]
```diff
@@ -132,7 +132,7 @@ async function runVercelBuild(
 	additionalArgs: string[] = [],
 ): Promise<void> {
 	if (pm.name === 'yarn' && pm.version.startsWith('1.')) {
-		const vercelInfo = await pm.getPackageInfo('vercel');
+		const vercelInfo = await pm.getPackageInfo('vercel').catch(() => null);
```
Comment (petebacondarwin) [inline packages/next-on-pages/src/buildApplication/buildVercelOutput.ts:135]: It feels like it would be good to wrap this call+catch into a helper function, to avoid having to remember to do it everywhere that `pm.getPackageInfo()` is used, no?

**Review by petebacondarwin — APPROVED** [review]

File: packages/next-on-pages/src/buildApplication/buildVercelOutput.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/next-on-pages/src/buildApplication/buildVercelOutput.ts]: Thanks! good call, I've added a helper function for that 🙂👍
