### PR TITLE
Make sure that trailingSlashes don't interfere with the path existence check

### LINKED ISSUE #593: [🐛 Bug]: dynamic page with catch all route overrides all API routes
### next-on-pages environment related information

```
System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
        CPU: (8) arm64 Apple M1
        Memory: 16 GB
        Shell: /bin/zsh
Package Manager Used: npm (10.2.3)

Relevant Packages:
        @cloudflare/next-on-pages: 1.8.2
        vercel: N/A
        next: 14.0.4
```

### Description

When using a catch all page routes on the top level (e.g. `/pages/[...slug].tsx` or  `/app/[...slug]/page.tsx`), all API routes incorrectly route to the catch all page instead of hitting the API endpoint.

Have also tried local dev server/builds and deployment to Vercel with the same codebase, but haven't been able to reproduce it in those environments, so it looks like it only affects `@cloudflare/next-on-pages` builds (both local `npx @cloudflare/next-on-pages` and on Cloudflare Pages deployment).

Problem occurs in both `app` and `page` routers.

### Reproduction

Regular catch all page (using `pages` router)
https://dynamic-routes-api-404.pages.dev/home/page/
https://dynamic-routes-api-404.vercel.app/home/page/

API route (using `pages` router):
https://dynamic-routes-api-404.pages.dev/api/hello/ (loads catch all page)
https://dynamic-routes-api-404.vercel.app/api/hello/ (loads API route)

Regular catch all page (using `app` router)
https://dynamic-routes-api-404-app.pages.dev/home/page/
https://dynamic-routes-api-404-app.vercel.app/home/page/

API route (using `app` router):
https://dynamic-routes-api-404-app.pages.dev/api/hello/  (loads catch all page)
https://dynamic-routes-api-404-app.vercel.app/api/hello/ (loads API route)

Repos for repro: 
Pages: https://github.com/fong/dynamic-routes-api-404 
App: https://github.com/fong/dynamic-routes-api-404-app

### Pages Deployment Method

Pages CI (GitHub/GitLab integration)

### Pages Deployment ID

b61f75ac

### Additional Information

_No response_

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
resolves #593

### CODE REVIEW

File: packages/next-on-pages/templates/_worker.js/routes-matcher.ts [hunk 1]
```diff
@@ -608,10 +608,9 @@ export class RoutesMatcher {
 
 		let pathExistsInOutput = this.path in this.output;
 
-		// If a path with a trailing slash entered the `rewrite` phase and didn't find a match, it might
-		// be due to the `trailingSlash` setting in `next.config.js`. Therefore, we should remove the
-		// trailing slash and check again before entering the next phase.
-		if (phase === 'rewrite' && !pathExistsInOutput && this.path.endsWith('/')) {
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/routes-matcher.ts:614]: @james-elicx do you remember by any chance if there was a specific reason for the check to only apply in the `rewrite` phase?

Comment (james-elicx) [reply packages/next-on-pages/templates/_worker.js/routes-matcher.ts:614]: I think it was something to do with certain trailing slash ones being rewritten in the rewrite phase, but others missing the rewrite they need which is what this was fixing. I don't *think* it would be problematic doing it in other phases, but that would be pretty hard to tell to be honest

Comment (dario-piotrowicz) [reply packages/next-on-pages/templates/_worker.js/routes-matcher.ts:614]: yes, that's my feeling too, I think we can just go with it and see how it performs in the wild, if it becomes problematic we can always restrict on which routes this applies to

All the e2e pass and [next-apps-for-testing apps](https://github.com/dario-piotrowicz/next-apps-for-testing/actions/runs/7208472507) also seem to be totally fine (I've checked a handful of them), so it does look to me like a pretty safe change to make

**Review by jculvey — APPROVED** [review]
