### PR TITLE
fix wasmImportsToPrepend overriding existing imports

### LINKED ISSUE #494: [🐛 Bug]: next-on-pages removes wasm imports from production build
### next-on-pages environment related information

```console
System:
        Platform: linux
        Arch: x64
        Version: #1 SMP PREEMPT_DYNAMIC Sat Sep 23 22:53:27 UTC 2023
        CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
        Memory: 31 GB
        Shell: /usr/bin/zsh
Binaries:
        Node: 20.8.0
        Bun: N/A
        pnpm: N/A
        Yarn: N/A
        npm: 10.1.0
Package Manager Used: npm
Relevant Packages:
        @cloudflare/next-on-pages: 1.6.3
        vercel: N/A
        next: 13.5.4

```

### Description

when multiple files import wasm modules `next-on-pages` produces a broken production build.

```
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #1)
ReferenceError: wasm_59cd556b704b5c8ea09030c5838471a4b2299032 is not defined
    at Object.Bf (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/webpack/e3d30189dcd18971da5d91ca8a0b3626.js:56:33396)
    at n (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:2157)
    at Object.Vf (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/webpack/e3d30189dcd18971da5d91ca8a0b3626.js:56:35967)
    at n (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:2157)
    at 8046 (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:4291)
    at n (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:2157)
    at file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:6080
    at o (file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:3549)
    at file:///tmp/tmp-79001-VJJb8KyehEsA/__next-on-pages-dist__/functions/bananas/opengraph-image.func.js:1:3805 {
  stack: ReferenceError: wasm_59cd556b704b5c8ea09030c583847…/functions/bananas/opengraph-image.func.js:1:3805,
  message: wasm_59cd556b704b5c8ea09030c5838471a4b2299032 is not defined
}
```

it seems like `next-on-pages` removes wasm imports from the generated output files.

### Reproduction

https://github.com/blukai/next-on-pages-wasm-import-bug

in the reproduction repo when both directories `src/app/hmm` and `src/app/banana` are present - production build is broken.

everything works fine if wasm module is imported only once within a code base (to prove that - in the reproduction repo remove `src/app/hmm`  directory -> build the project (`npm run build:next-on-pages`) -> launch it `wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat` -> go to http://localhost:8788/bananas/opengraph-image -> it works).

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

_No response_

### Would you like to help?

- [X] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
when dealing with wasms that have more than 1 consumer, when we collect the wasm imports to prepend for a specific edge funcion we're always re-setting the array of wasm imports instead of appending them, this causes edge functions to always only consider the last wasm import, fix such issue

resolves #494

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
@james-elicx

File: packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts [hunk 1]
```diff
@@ -121,10 +121,10 @@ async function processFunctionIdentifiers(
...
 				if (newImport) importsToPrepend.push(newImport);
 				if (wasmImports.length) {
-					wasmImportsToPrepend.set(
-						identifierInfo.newDest as string,
-						wasmImports,
-					);
+					const newDest = identifierInfo.newDest as string;
+					const existingWasmImports = wasmImportsToPrepend.get(newDest) ?? [];
+					const newWasmImports = existingWasmImports.concat(wasmImports);
+					wasmImportsToPrepend.set(newDest, newWasmImports);
```
Comment (james-elicx) [inline packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts:127]: Please can you change the `wasmImportsToPrepend` map to use sets instead of arrays so that we ensure there are no duplicates added?

**Comment by dario-piotrowicz** [comment]
Regarding testing these changes, I think it would be practically impossible to test this with unit tests

I have been thinking of adding e2es for this and that would be totally feasible, but our e2es testing surface isn't currently very wide so I feel that spending time adding e2es for this change would be much less beneficial than adding e2es in other (more fundamental areas) (in other words, if I were to implement new e2es I think it my time would be much better spent testing other next features rather than this edge case scenario).

I'm totally happy to add e2es for this anyways if someone strongly believes that I should 🙂

File: packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts:127]: 😮 yeah! good point! thanks!

Comment (dario-piotrowicz) [reply packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts]: done 🙂👍

**Review by james-elicx — APPROVED** [review]
