### PR TITLE
fix: middleware redirects accidentally applying search params

### LINKED ISSUE #335: [🐛 Bug]: Redirecting in middleware causes query string parameters to be retained
### next-on-pages environment related information

Relevant Packages:
	@cloudflare/next-on-pages: 1.1.0

### Description

If you create a middleware and return a redirect like so:

```
return new Response('', {
        status: 302,
        headers: {
          Location: 'http://localhost:8788/',
        }
      })
```

If the original request URL has query string parameters like `?foo=bar`, the Location header will be `http://localhost:8788/?foo=bar` which is not the intended redirect URL.

Same behaviour is exhibited if using `Response.redirect` or `NextResponse.redirect`.

This seems to be causing the issue: https://github.com/cloudflare/next-on-pages/blob/2c8748176ffed5d50585bd86e14b1f2c974d0c96/packages/next-on-pages/templates/_worker.js/handleRequest.ts#L75

Commenting this out and just returning the unmodified Location header results in the correct Location header being returned.

### Reproduction

_No response_

### Pages Deployment Method

Direct Upload (`wrangler pages publish` or the @cloudflare/pages-action GitHub Action)

### Pages Deployment ID

_No response_

### Additional Information

_No response_

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by james-elicx**
This PR does the following:
- Stops applying the search parameters to the `location` header if it is from a middleware.

This appears to be how it behaves in `next dev` for middleware, so I'm happy for this logic to be removed.

fixes #335

### CODE REVIEW

File: packages/next-on-pages/templates/_worker.js/utils/routing.ts [hunk 1]
```diff
@@ -6,10 +6,16 @@ import {
 	applySearchParams,
 } from './http';
 
+export type MatchedSetHeaders = {
+	normal: Headers;
+	important: Headers;
+	middlewareLocation?: string | null;
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/utils/routing.ts:12]: could you add a comment explaining that this is not standard and why (and how) we need to use it? 🙏

File: packages/next-on-pages/templates/_worker.js/handleRequest.ts [hunk 2]
```diff
@@ -71,13 +71,15 @@ async function generateResponse(
...
-	if (headers.normal.has('location')) {
-		// Apply the search params to the location header.
-		const location = headers.normal.get('location') ?? '/';
-		const paramsStr = [...searchParams.keys()].length
-			? `?${searchParams.toString()}`
-			: '';
-		headers.normal.set('location', `${location}${paramsStr}`);
+	const locationHeader = headers.normal.get('location');
+	if (locationHeader) {
+		// Apply the search params to the location header if it was not from middleware.
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/handleRequest.ts:76]: Could you add a comment saying why it should not come from the middleware? 🙏

File: .changeset/large-pillows-try.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@cloudflare/next-on-pages": patch
+---
+
+Prevent middleware redirects applying search params.
```
Comment (dario-piotrowicz) [inline .changeset/large-pillows-try.md:5]: Could you expand/clarify/show an example in the changeset? 🙏

**Review by dario-piotrowicz — APPROVED** [review]
Thanks a lot @james-elicx 😃 

I've just added some comments asking to add more comments/context to the changes as I think that later on it might be quite hard to understand/remember why these changes are here
