### PR TITLE
Fix autogenerated append to original _headers file

### LINKED ISSUE #848: [🐛 Bug]: next-on-pages repeatedly appends to _headers
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2
        CPU: (12) x64 AMD Ryzen 9 5900X 12-Core Processor
        Memory: 20 GB
        Shell: /bin/bash
Package Manager Used: npm (10.5.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.13.1
        vercel: N/A
        next: 14.2.5
```

### Description

Each invocation of:

```
npx @cloudflare/next-on-pages@1
```

Appends another instance of:

```
# === START AUTOGENERATED @cloudflare/next-on-pages IMMUTABLE HEADERS ===
/_next/static/*
  cache-control: public,max-age=31536000,immutable
# === END AUTOGENERATED @cloudflare/next-on-pages IMMUTABLE HEADERS ===
```

to `public/_headers`. Which doesn't seem right. I would expect only `.vercel/output/static/_headers` to contain the auto generated content and not `public/_headers` too

### Reproduction

```bash
npx create-next-app@latest my-next-app
cd my-next-app
npm install -D @cloudflare/next-on-pages
touch public/_headers
npx @cloudflare/next-on-pages@1
cat public/_headers
```

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

The bug is due to vercel hardlinking public assets directory.

https://github.com/vercel/vercel/blob/8e20fed2769ff0169179d2d40fcc97cfd07a8bfe/packages/gatsby-plugin-vercel-builder/src/helpers/static.ts#L15

Perhaps next-on-pages takes matters into their own hands with the equivalent of:

```bash
# vercel build ...
[[ -f public/_headers ]] && cp --remove-destination public/_headers .vercel/output/static/_headers
echo "AUTOGENERATED ..." >> .vercel/output/static/_headers
```

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by nickbabcock**
Vercel hard links the public directory so when next-on-pages appends to file within the vercel output directory, it is also appending to the original `public/_headers` file too.

This commit fixes the problem by copying the contents to memory before unlinking the file and creating a new (non-linked) file.

I was able to test out this patch and saw it worked for when `_headers` exists and when it is absent.

Closes #848

### CODE REVIEW

File: packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts [hunk 1]
```diff
@@ -40,22 +40,36 @@ async function buildNextStaticHeaders(
...
-# === END AUTOGENERATED @cloudflare/next-on-pages IMMUTABLE HEADERS ===\n`,
-			{
-				// in case someone configured redirects already, append to the end
-				flag: 'a',
-			},
-		);
+# === END AUTOGENERATED @cloudflare/next-on-pages IMMUTABLE HEADERS ===\n`;
+
+	try {
+		// Vercel hard links the public directory. We need to unlink before we
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts:58]: Could you please include `https://github.com/vercel/vercel/blob/8e20fe/packages/gatsby-plugin-vercel-builder/src/helpers/static.ts#L15` in your comment so that we have a reference to the actual Vercel source code? 🙂🙏

**Review by dario-piotrowicz — APPROVED** [review]
Looks great to me! Thanks a bunch @nickbabcock 🙂 ❤️ 

I've just left a minor comment, also could you run `npm run prettier:fix` to format the code? 🙂🙏

File: packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts (hunk 1 above)
Comment (nickbabcock) [reply packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts]: Good point. I ended up using a different code location that is more accurate. It's the same issue (static files being hard linked) but is not gatsby specific.

**Comment by nickbabcock** [comment]
Comments addressed, thank you 🙏

File: packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts [hunk 2]
```diff
@@ -40,22 +40,37 @@ async function buildNextStaticHeaders(
...
-			{
-				// in case someone configured redirects already, append to the end
-				flag: 'a',
-			},
-		);
+# === END AUTOGENERATED @cloudflare/next-on-pages IMMUTABLE HEADERS ===\n`;
+
+	try {
+		// Vercel hard links the static files directory:
+		// https://github.com/vercel/vercel/blob/8e20fed2769ff0169179d2d40fcc97cfd07a8bfe/packages/cli/src/util/build/write-build-result.ts#L336
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts:59]: we usually shorten the sha not to make the line too long 🙂 
```suggestion
		// https://github.com/vercel/vercel/blob/8e20fed/packages/cli/src/util/build/write-build-result.ts#L336
```

File: .changeset/breezy-walls-stare.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@cloudflare/next-on-pages': patch
+---
+
+Fix autogenerated append to original \_headers file
```
Comment (dario-piotrowicz) [inline .changeset/breezy-walls-stare.md:5]:
```suggestion
Fix autogenerated content also getting appended to the original public/\_headers file
```

**Review by dario-piotrowicz — APPROVED** [review]
Looks great! thanks a lot for updating the comment and formatting the code 🙏 

I've left two minor very last comments 😅 🙇

File: packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts]: ah great! 😄 

I didn't even notice the link was gatsby specific 🙈

**Comment by dario-piotrowicz** [comment]
Once again thanks a lot @nickbabcock 🫶
