### PR TITLE
fix: named captures in `has` fields not applying to route dest

### LINKED ISSUE #448: [🐛 Bug]: Rewrites with `has` query option doesn't behave as expected
### next-on-pages environment related information

<details>
  <summary>env info</summary>

```
  System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
	CPU: (8) arm64 Apple M2
	Memory: 8 GB
	Shell: /opt/homebrew/bin/zsh
  Binaries:
	Node: 18.17.0
	Bun: N/A
	pnpm: N/A
	Yarn: 1.22.19
	npm: 9.6.7
  Package Manager Used: yarn (classic)
  Relevant Packages:
	@cloudflare/next-on-pages: 1.6.0
	vercel: 32.1.0
	next: 13.4.19
```
</details>

### Description

Hi there,

During deployment we've noticed an issue which only seems to affect our project once deployed via next-on-pages. The issue pertains to Next's 'rewrites' config option which doesn't _appear_ to be supported properly at the moment.

On the [supported doc](https://github.com/cloudflare/next-on-pages/blob/main/packages/next-on-pages/docs/supported.md) it does state that "routes `has`" is supported; at present however I think some of the behaviour is not supported. For example, the following "rewrites" config:

```
async rewrites() {
    return {
      beforeFiles: [{
          source: '/user-query',
          has: [{
              type: 'query',
              key: 'name',
              value: '(?<name>.*)',
          }],
          destination: '/user/:name',
      }],
    };
  },
```

Which aims to rewrite "/user-query?name=bacon" to "/user/bacon". This does not appear to work correctly in next-on-pages. I'm not sure if this is a particularly unusual pattern or not but does seem to follow the docs on nextjs and does work when running in development or production build with next. It appears to only fail when locally using `wrangler` or when deployed to a preview URL on Cloudflare.

I also believe fixing this could fix some of the issues with `@sentry/nextjs` as their tunnelling option makes use of a very similar rewrite under-the-hood.

<details>
  <summary>@sentry/nextjs rewrite option</summary>

  ```
    {
      // Matched rewrite routes will look like the following: `[tunnelPath]?o=[orgid]&p=[projectid]`
      // Nextjs will automatically convert `source` into a regex for us
      source: `${tunnelPath}(/?)`,
      has: [
        {
          type: 'query',
          key: 'o', // short for orgId - we keep it short so matching is harder for ad-blockers
          value: '(?<orgid>.*)',
        },
        {
          type: 'query',
          key: 'p', // short for projectId - we keep it short so matching is harder for ad-blockers
          value: '(?<projectid>.*)',
        },
      ],
      destination: 'https://o:orgid.ingest.sentry.io/api/:projectid/envelope/',
    }
  ```
</details>

### Reproduction

https://github.com/emma-cw/next-pages-rewrites-test

Pulling this repo and running with `npm run dev`/`yarn dev` will run successfully and the rewrite will behave as expected. For example `http://localhost:3000/user/bacon` and `http://localhost:3000/user-query?name=bacon` will display the same very basic page.

However if running with `npx @cloudflare/next-on-pages@1` and then `npx wrangler pages dev .vercel/output/static --compatibility-flag=nodejs_compat` the rewrite no longer functions as expected. Instead,  `http://localhost:8788/user/bacon` will show correctly but `http://localhost:8788/user-query?name=bacon` will return `404` instead.

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

_No response_

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by james-elicx**
This PR does the following:
- Changes the logic to use the PCRE match function for `has` entries as the regex is expected to be in the PCRE format.
- For PCRE matches in the `has` entries, attempts to update the route's destination with any named capture groups extracted.

Relevant docs: https://nextjs.org/docs/app/api-reference/next-config-js/rewrites#header-cookie-and-query-matching

fixes #448

### CODE REVIEW

**Comment by emma-cw** [comment]
Would be amazing if we could proceed with this PR 🙏  it will help out a lot and should also help with support for @sentry/nextjs

**Comment by james-elicx** [comment]
> Would be amazing if we could proceed with this PR 🙏 it will help out a lot and should also help with support for @sentry/nextjs

Hello @emma-cw, Dario is OOO at the moment and will take a look at this when he gets back 🙂. So, I'm afraid it might take a little longer than usual.

You can of course keep using the prerelease until this is merged though!

File: packages/next-on-pages/templates/_worker.js/utils/matcher.ts [hunk 1]
```diff
@@ -13,34 +17,64 @@ type HasFieldRequestProperties = {
...
+			return { valid: url.hostname === has.value };
 		}
 		case 'header': {
 			if (has.value !== undefined) {
-				return !!headers.get(has.key)?.match(has.value);
+				const match = matchPCRE(has.value, headers.get(has.key));
+				return {
+					valid: !!match.match,
+					newRouteDest: tryApplyMatch(routeDest, match),
+				};
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/utils/matcher.ts:32]: The current implementation seems to always have this `matchPCRE` + return object code, so there is a bit of code duplication, I've tried to remove the code duplication and ended up with something like this:
```diff
diff --git a/packages/next-on-pages/templates/_worker.js/utils/matcher.ts b/packages/next-on-pages/templates/_worker.js/utils/matcher.ts
index 666ae895..f1e40aed 100644
--- a/packages/next-on-pages/templates/_worker.js/utils/matcher.ts
+++ b/packages/next-on-pages/templates/_worker.js/utils/matcher.ts
@@ -1,4 +1,3 @@
-import type { MatchPCREResult } from './pcre';
 import { applyPCREMatches, matchPCRE } from './pcre';
 
 type HasFieldRequestProperties = {
@@ -17,7 +16,7 @@ type HasFieldRequestProperties = {
  */
 export function hasField(
        has: VercelHasField,
-       { url, cookies, headers, routeDest }: HasFieldRequestProperties,
+       { url, cookies, headers, routeDest }: HasFieldRequestProperties
 ): { valid: boolean; newRouteDest?: string } {
        switch (has.type) {
                case 'host': {
@@ -25,11 +24,12 @@ export function hasField(
                }
                case 'header': {
                        if (has.value !== undefined) {
-                               const match = matchPCRE(has.value, headers.get(has.key));
-                               return {
-                                       valid: !!match.match,
-                                       newRouteDest: tryApplyMatch(routeDest, match),
-                               };
+                               return getHasFieldPCREMatchResult(
+                                       has.value,
+                                       routeDest,
+                                       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+                                       headers.get(has.key)!
+                               );
                        }
 
                        return { valid: headers.has(has.key) };
@@ -38,22 +38,18 @@ export function hasField(
                        const cookie = cookies[has.key];
 
                        if (cookie && has.value !== undefined) {
-                               const match = matchPCRE(has.value, cookie);
-                               return {
-                                       valid: !!match.match,
-                                       newRouteDest: tryApplyMatch(routeDest, match),
-                               };
+                               return getHasFieldPCREMatchResult(has.value, routeDest, cookie);
                        }
 
                        return { valid: cookie !== undefined };
                }
                case 'query': {
                        if (has.value !== undefined) {
-                               const match = matchPCRE(has.value, url.searchParams.get(has.key));
-                               return {
-                                       valid: !!match.match,
-                                       newRouteDest: tryApplyMatch(routeDest, match),
-                               };
+                               return getHasFieldPCREMatchResult(
+                                       has.value,
+                                       routeDest,
+                                       url.searchParams.get(has.key) ?? ''
+                               );
                        }
 
                        return { valid: url.searchParams.has(has.key) };
@@ -62,19 +58,33 @@ export function hasField(
 }
 
 /**
- * Try to apply a PCRE match's named capture groups to a destination.
+ * Gets the has field result from a PCRE match
  *
- * @param dest Destination to apply match to.
- * @param match Matched PCRE result.
- * @returns The destination with the match applied, or `undefined` if there was no match.
+ * @param hasValue the value of the has field
+ * @param routeDest original route destination
+ * @param target target string to match
+ * @returns an object indicating if the match is valid and the new route destination if existent
  */
-function tryApplyMatch(
-       dest: string | undefined,
-       { match, captureGroupKeys }: MatchPCREResult,
-): string | undefined {
-       if (dest && match && captureGroupKeys.length) {
-               return applyPCREMatches(dest, match, captureGroupKeys, { namedOnly: true });
+function getHasFieldPCREMatchResult(
+       hasValue: string,
+       routeDest: string | undefined,
+       target: string
+): ReturnType<typeof hasField> {
+       const match = matchPCRE(hasValue, target);
+       let newRouteDest: string | undefined = undefined;
+
+       // if there are capture groups apply them to get a new route destination
+       if (routeDest && match.match && match.captureGroupKeys.length) {
+               newRouteDest = applyPCREMatches(
+                       routeDest,
+                       match.match,
+                       match.captureGroupKeys,
+                       { namedOnly: true }
+               );
        }
 
-       return undefined;
+       return {
+               valid: !!match.match,
+               newRouteDest,
+       };
 }
```

I __think__ something along these lines might be nicer but I am not completely sure, what do you think?

If you prefer the current implementation I'm totally fine to go with it as well 🙂

File: packages/next-on-pages/templates/_worker.js/utils/matcher.ts [hunk 2]
```diff
@@ -13,34 +17,64 @@ type HasFieldRequestProperties = {
  */
 export function hasField(
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/utils/matcher.ts:18]: Given the new return type I think the name of this function needs to be updated 🤔 
```suggestion
export function checkHasField(
```
(or something along these lines)

Comment (dario-piotrowicz) [reply packages/next-on-pages/templates/_worker.js/utils/matcher.ts:18]: Also, could you please update the tsdoc comment?

the function description can clarify that performs a check and returns the new destination (if it exists) also the return says ``* @returns Whether the request matches the `has` record conditions.`` which is no longer totally correct

File: packages/next-on-pages/templates/_worker.js/utils/pcre.ts [hunk 3]
```diff
@@ -43,9 +47,16 @@ export function applyPCREMatches(
 	rawStr: string,
 	match: RegExpMatchArray,
 	captureGroupKeys: string[],
+	{ namedOnly }: { namedOnly?: boolean } = {},
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/utils/pcre.ts:50]: could you add this in the tsdoc comment? 👆

**Review by dario-piotrowicz — COMMENTED** [review]
Thanks a lot @james-elicx 😃 

Sorry I left some minor comments, but nothing major just small naming bits and whatnot to amend 🙂

**Comment by dario-piotrowicz** [comment]
I'm back, thanks a lot @james-elicx for the PR and sorry (both to you and @emma-cw) for the delay in reviewing it 🙇

File: packages/next-on-pages/templates/_worker.js/utils/matcher.ts (hunk 1 above)
Comment (james-elicx) [reply packages/next-on-pages/templates/_worker.js/utils/matcher.ts:32]: I could have bet money on you replying this!! I aaallllllmmmmoooossstttt made that change earlier this week in anticipation that you might say that. 😅

Comment (dario-piotrowicz) [reply packages/next-on-pages/templates/_worker.js/utils/matcher.ts:32]: sorry for being too predictable 🙈 

anyways as I said it's just a suggestion, I'm totally ok with your solution too

my suggestion also isn't any shorter (I hoped it would be before writing it) so I don't think it's objectively better

**Review by dario-piotrowicz — APPROVED** [review]
Awesome! Thanks a lot @james-elicx  😄
