### PR TITLE
fix: broken rewrites for __index.prefetch.rsc

### LINKED ISSUE #542: [🐛 Bug]: Request to ?_rsc=* returns 404 and app is no more SPA
### next-on-pages environment related information

```
System:
        Platform: linux
        Arch: x64
        Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
        CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
        Memory: 3 GB
        Shell: /bin/bash
Package Manager Used: npm (10.1.0)

Relevant Packages:
        @cloudflare/next-on-pages: 1.7.3
        vercel: 32.5.5
        next: 14.0.3
```

### Description

The app is making request to {url}/?_rsc={random_string} and it responses with 404 status code also navigating to other pages hard reloads the page when app is build using `npx @cloudflare/next-on-pages`.
Note that this issue only appears in production mode (built using `npx @cloudflare/next-on-pages`).

Here are screenshots of devtools:
**In production mode** (`npx @cloudflare/next-on-pages`):

image

image

image

**In development mode** (`next dev`) **or production mode** (`next build && next start`):

image

image

### Reproduction

See: https://github.com/techwithdeo/next-pages-test

1. `git clone git@github.com:techwithdeo/next-pages-test.git`
2. `cd next-pages-test`
3. `npm install`
4. `npm run pages:build`
5. `npm run pages:serve`
6. Open DevTools
7. Navigate to /contact

**Works fine ✅ when:**

1. `npm run build`
2. `npm start`

### Pages Deployment Method

*Not yet deployed*

### Pages Deployment ID

*Not yet deployed*

### Additional Information

_No response_

### Would you like to help?

- [ ] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by james-elicx**
This PR does the following:
- Fixes the logic for rewriting rsc requests so that it correctly handles `/__index.prefetch.rsc` -- it was previously rewriting those requests to `/__index` which resulted in a 404.
- Stops stripping the `.prefetch.rsc` suffix as these are correctly stripped by Vercel at a later phase in the build output config.

fixes #542

### CODE REVIEW

File: packages/next-on-pages/templates/_worker.js/routes-matcher.ts [hunk 1]
```diff
@@ -316,17 +316,22 @@ export class RoutesMatcher {
 		// NOTE: Special handling for `/index` RSC routes. Sometimes the Vercel build output config
 		// has a record to rewrite `^/` to `/index.rsc`, however, this will hit requests to pages
 		// that aren't `/`. In this case, we should check that the previous path is `/`.
-		if (/\/index\.rsc$/i.test(this.path) && !/^\/(?:index)?$/i.test(prevPath)) {
+		const isRscIndex = /\/index\.rsc$/i.test(this.path);
+		const isPrevAbsoluteIndex = /^\/(?:index)?$/i.test(prevPath);
+		const isPrevPrefetchRscIndex = /^\/__index\.prefetch\.rsc$/i.test(prevPath);
```
Comment (dario-piotrowicz) [inline packages/next-on-pages/templates/_worker.js/routes-matcher.ts:321]: a comment (and source code link) to this `__index.preferch.rsc` would be great :slightly_smiling_face:

File: .changeset/sixty-wolves-type.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@cloudflare/next-on-pages': patch
+---
+
+Fix broken `__index.prefetch.rsc` rewrites.
```
Comment (dario-piotrowicz) [inline .changeset/sixty-wolves-type.md:5]: if you could add a bit more context here (what this actually fixes) that'd be nice, but if you feel like this is enough I am ok with it :slightly_smiling_face:

**Review by dario-piotrowicz — APPROVED** [review]
Looks great! thanks a lot @james-elicx :smiley: 

(I just left two minor comments/suggestion :slightly_smiling_face:)
